spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://localhost:3306/schedule-db
    username: user
    password: pass